language: minimal
os: osx
osx_image:
  - xcode12.3 # Big Sur

branches:
  only:
  - main

before_install:
  - ansible-galaxy collection install -r requirements.yaml

script:
  - ansible-playbook macos.yaml
