- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
